[CmdletBinding()]
param(
    [switch]$SkipDependencies,
    [switch]$SkipBuild,
    [switch]$NonInteractive,
    [switch]$IncludeCloudflare
)

$ErrorActionPreference = 'Stop'
$projectRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$configPath = Join-Path $projectRoot 'config.local.json'
$runtimeRoot = Join-Path $projectRoot 'var'
$utf8NoBom = New-Object Text.UTF8Encoding($false)

function Get-PrivateNetworkCIDR {
    $candidate = Get-NetIPConfiguration -ErrorAction SilentlyContinue |
        Where-Object { $_.IPv4DefaultGateway -and $_.IPv4Address } |
        ForEach-Object { $_.IPv4Address } |
        Where-Object { $_.IPAddress -match '^(10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)' } |
        Select-Object -First 1
    if (-not $candidate) { return $null }

    $bytes = [Net.IPAddress]::Parse($candidate.IPAddress).GetAddressBytes()
    $prefix = [int]$candidate.PrefixLength
    for ($index = 0; $index -lt 4; $index++) {
        $remaining = $prefix - ($index * 8)
        $mask = if ($remaining -ge 8) { 255 } elseif ($remaining -le 0) { 0 } else { (0xFF -shl (8 - $remaining)) -band 0xFF }
        $bytes[$index] = $bytes[$index] -band $mask
    }
    return ([Net.IPAddress]::new($bytes).ToString() + '/' + $prefix)
}

function Test-IPv4CIDR {
    param([string]$Value)
    $parts = $Value.Split('/', 2)
    if ($parts.Count -ne 2) { return $false }
    $address = $null
    $prefix = 0
    return [Net.IPAddress]::TryParse($parts[0], [ref]$address) -and
        $address.AddressFamily -eq [Net.Sockets.AddressFamily]::InterNetwork -and
        [int]::TryParse($parts[1], [ref]$prefix) -and $prefix -ge 0 -and $prefix -le 32
}

Write-Host ''
Write-Host 'ProxyTunnel first-time setup' -ForegroundColor Cyan
$writeConfiguration = $true
if (Test-Path -LiteralPath $configPath) {
    if ($NonInteractive) {
        $writeConfiguration = $false
    } else {
        $replaceAnswer = Read-Host 'config.local.json already exists. Replace it with the new minimal configuration? [y/N]'
        $writeConfiguration = $replaceAnswer -match '^(y|yes)$'
    }
}
if ($writeConfiguration) {
    $allowedCIDR = '127.0.0.0/8'
    $lanAnswer = if ($NonInteractive) { 'n' } else {
        Write-Host 'Press Enter for the safe default: only this computer can open the console.'
        Read-Host 'Allow trusted LAN computers to access the console? [y/N]'
    }
    if ($lanAnswer -match '^(y|yes)$') {
        $detectedCIDR = Get-PrivateNetworkCIDR
        if (-not $detectedCIDR) {
            throw 'No private IPv4 network with a default gateway was detected. Run setup again after networking is ready.'
        }
        Write-Host "Detected trusted network: $detectedCIDR" -ForegroundColor Yellow
        $confirmCIDR = Read-Host 'Use this network? [Y/n]'
        if ($confirmCIDR -match '^(n|no)$') {
            $detectedCIDR = Read-Host 'Enter the trusted CIDR, for example 192.168.1.0/24'
        }
        if (-not (Test-IPv4CIDR $detectedCIDR)) {
            throw 'The trusted CIDR format is invalid.'
        }
        $allowedCIDR = $detectedCIDR
    }
    $configuration = [ordered]@{
        '$comment' = 'Generated by START.cmd. Every omitted option uses a safe project default.'
        allowed_cidr = $allowedCIDR
    }
    [IO.File]::WriteAllText($configPath, (($configuration | ConvertTo-Json) + [Environment]::NewLine), $utf8NoBom)
} else {
    Write-Host 'Existing config.local.json was preserved.' -ForegroundColor Yellow
}

foreach ($relativePath in @(
    'history', 'logs', 'run', 'secrets', 'state',
    'main-pool', 'main-pool\providers', 'probe', 'probe\providers',
    'custom-pool', 'pool-builds', 'pool-profiles'
)) {
    $target = Join-Path $runtimeRoot $relativePath
    if (-not (Test-Path -LiteralPath $target)) {
        New-Item -ItemType Directory -Path $target -Force | Out-Null
    }
}

$mainSecretPath = Join-Path $runtimeRoot 'secrets\main-controller.secret'
if (-not (Test-Path -LiteralPath $mainSecretPath)) {
    New-Item -ItemType File -Path $mainSecretPath -Force | Out-Null
}

if (-not $SkipDependencies) {
    if ($IncludeCloudflare) {
        & (Join-Path $PSScriptRoot 'bootstrap.ps1')
    } elseif (-not (Get-Command go -ErrorAction SilentlyContinue)) {
        throw 'Go is required for the first local build. Install Go 1.26 or newer, then run START.cmd again.'
    }
}
if (-not $SkipBuild) {
    & (Join-Path $PSScriptRoot 'build.ps1')
}

Write-Host ''
Write-Host 'Setup complete.' -ForegroundColor Green
Write-Host "Local configuration: $configPath"
if ($writeConfiguration) {
    Write-Host "Allowed management network: $allowedCIDR"
} else {
    Write-Host 'Allowed management network: unchanged (existing configuration preserved)'
}
Write-Host 'No Cloudflare account, KV namespace, domain, or production service was changed.'
